/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import entidades.Cuentas;
import database.BaseDatos;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author CATV
 */
public class Ajustes extends JPanel {

    /**
     * Creates new form Ajustes
     */
    Ventana ven;
//    Cuentas cuenta;
    String correo;

    public Ajustes(Ventana ven, String correo) {
        this.ven = ven;
        this.correo = correo;
        initComponents();
//        cuenta = new Cuentas();
        jLabel5.setText(correo);
    }

    public Ajustes() {
        initComponents();
    }

    public /*boolean*/ void info() {//recuperar -----> info
        /*   boolean flag = false;
         BaseDatos base = new BaseDatos();
         String cifrado = Cuentas.Encriptar(PedirContra('v'));
         Cuentas cuentaTemp = new Cuentas(correo);

         if (base.crearConexion()) {
         LinkedList<Object> list = base.read(cuentaTemp.select());

         if (!list.isEmpty()) {
         cuenta.read(list);
         if (cifrado.equals(cuenta.getPassword())) {*/
        jNombre.setText(ven.cuenta.getNombre());// cuenta  ----> ven.cuenta
        jApellido.setText(ven.cuenta.getApellido());// cuenta  ----> ven.cuenta
        jCelular.setText(ven.cuenta.getCelular());// cuenta  ----> ven.cuenta

        /*    flag = true;
         } else {
         flag = false;
         }
         }
         }
         return flag;*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jApellido = new javax.swing.JTextField();
        BtActualizar = new javax.swing.JButton();
        jCelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        BtCambiar = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("Celular");

        BtActualizar.setText("Actualizar");
        BtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtActualizarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jNombre.setToolTipText("");

        BtCambiar.setText("Modificar");
        BtCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCambiarActionPerformed(evt);
            }
        });

        BtEliminar.setText("Eliminar");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });

        jLabel7.setText("Eliminar cuenta");

        jLabel8.setText("Modificar contraseña");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtActualizar)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtEliminar)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(BtCambiar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(jCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtActualizar)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(BtCambiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtEliminar)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtActualizarActionPerformed

//        String Contraseña = JOptionPane.showInputDialog("Ingrese contraseña, para guardar");
        BaseDatos base = new BaseDatos();
        if (base.crearConexion()) {
            String Nombre = jNombre.getText();
            String cifrado = Cuentas.Encriptar(ven.cuenta.getPassword());// cuenta  ----> ven.cuenta
            String Apellido = jApellido.getText();
            String Celular = jCelular.getText();
            String Correo = ven.cuenta.getCorreo();// cuenta  ----> ven.cuenta

            Cuentas cuentaTemp = new Cuentas(Correo, cifrado, Nombre, Apellido, Celular);

            base.update(cuentaTemp.update());
            ven.cuenta = cuentaTemp;// se debe actualizar la CUENTA de VENTANA

            jPCuenta reg = new jPCuenta(ven);// sitios
            ven.setContentPane(reg);
            ven.setSize(410, 350);

        } else {
            JOptionPane.showMessageDialog(null, "La contraseña no coincide");
        }
    }//GEN-LAST:event_BtActualizarActionPerformed

    public String PedirContra(char c) {
        String password = null;
        JPasswordField pf;

        switch (c) {
            case 'v':
                pf = new JPasswordField();
                int pPass = JOptionPane.showConfirmDialog(null, pf, "Ingrese contraseña", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (pPass == JOptionPane.OK_OPTION) {
                    password = new String(pf.getPassword());
//                    System.err.println("You entered: " + password);
                }
                break;

            case 'n':
                pf = new JPasswordField();
                int pPass2 = JOptionPane.showConfirmDialog(null, pf, "Ingrese contraseña nueva", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (pPass2 == JOptionPane.OK_OPTION) {
                    password = new String(pf.getPassword());
//                    System.err.println("You entered: " + password);
                }
                break;

        }
        return password;

    }

    private void BtCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCambiarActionPerformed

        String cifrado = Cuentas.Encriptar(PedirContra('v'));
        BaseDatos base = new BaseDatos();
        if (base.crearConexion()) {
            if (cifrado.equals(ven.cuenta.getPassword())) {// cuenta  ----> ven.cuenta

                String cifrada = Cuentas.Encriptar(PedirContra('n'));

                String Correo = ven.cuenta.getCorreo();// cuenta  ----> ven.cuenta

                Cuentas cuentaTemp = new Cuentas(Correo, cifrada);

                base.update(cuentaTemp.update());
                ven.cuenta = cuentaTemp;// actualizar CUENTA de VENTANA

                JOptionPane.showMessageDialog(null, "Cambio realizado");

                jPCuenta reg = new jPCuenta(ven);
                ven.setContentPane(reg);
                ven.setSize(410, 350);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña invalida");
        }
    }//GEN-LAST:event_BtCambiarActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed

        String cifrado = Cuentas.Encriptar(PedirContra('v'));
        BaseDatos base = new BaseDatos();
        if (base.crearConexion()) {
            if (cifrado.equals(ven.cuenta.getPassword())) {

                String Correo = ven.cuenta.getCorreo();

                System.out.println("correo :" + Correo);

                Cuentas cuentaTemp = new Cuentas(Correo, cifrado);

                base.delete(cuentaTemp.delete());
                ven.cuenta = null;

                JOptionPane.showMessageDialog(null, "Cuenta eliminada");

                jPCuenta reg = new jPCuenta(ven);
                ven.setContentPane(reg);
                ven.setSize(410, 350);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña invalida");
        }

    }//GEN-LAST:event_BtEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtActualizar;
    private javax.swing.JButton BtCambiar;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JTextField jApellido;
    private javax.swing.JTextField jCelular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNombre;
    // End of variables declaration//GEN-END:variables
}
