/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import database.BaseDatos;
import entidades.Contenidos_Multimedia;
import entidades.Imagenes;
import entidades.Sitios_Interes;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author CATV
 */
public class MenuAdmin extends JPanel {

    Ventana ven;
    LinkedList<Sitios_Interes> sitios;
    ImageIcon imagen;

    /**
     * Creates new form PAg
     *
     * @param ven
     */
    public MenuAdmin(Ventana ven) {
        initComponents();
        this.ven = ven;
        sitios = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlista = new javax.swing.JComboBox<>();
        Jinsert = new javax.swing.JButton();
        JDelete = new javax.swing.JButton();
        JMod = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JDireccion = new javax.swing.JTextField();
        JInfo = new javax.swing.JTextField();
        JCalificacion = new javax.swing.JComboBox<>();
        JReseña = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JHorario = new javax.swing.JTextField();
        JImagen = new javax.swing.JLabel();
        JAdd = new javax.swing.JButton();
        JAtras = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(662, 374));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro Comercial", "Hotel", "Restaurante" }));
        Jlista.setSelectedIndex(1);
        add(Jlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 209, -1));

        Jinsert.setText("Insertar");
        Jinsert.setEnabled(false);
        Jinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JinsertActionPerformed(evt);
            }
        });
        add(Jinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        JDelete.setText("Borrar");
        JDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDeleteActionPerformed(evt);
            }
        });
        add(JDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        JMod.setText("Modificar");
        JMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JModActionPerformed(evt);
            }
        });
        add(JMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        add(JNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 223, -1));

        jLabel2.setText("Direccion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setText("Calificacion");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setText("Reseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 196, -1, -1));

        jLabel5.setText("Informacion adicional");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, -1, -1));
        add(JDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 223, -1));
        add(JInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 223, 66));

        JCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        JCalificacion.setSelectedIndex(1);
        add(JCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        JReseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JReseñaActionPerformed(evt);
            }
        });
        add(JReseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 223, 66));

        jLabel6.setText("Horario");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        add(JHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 137, 223, -1));
        add(JImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 40, 220, 230));

        JAdd.setText("Agregar");
        JAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAddActionPerformed(evt);
            }
        });
        add(JAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 281, -1, -1));

        JAtras.setText("Atras");
        JAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAtrasActionPerformed(evt);
            }
        });
        add(JAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void JinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JinsertActionPerformed

        BaseDatos base = new BaseDatos();
        Contenidos_Multimedia cont;
        //Cuentas cuenta = ven.cuenta;
        Sitios_Interes sitioTemp;
        //Contenidos_Multimedia conttemp;
        Imagenes img;

        String nombre = JNombre.getText();
        String dir = JDireccion.getText();
        int calificacion = Integer.parseInt(JCalificacion.getSelectedItem().toString());
        String horario = JHorario.getText();
        String reseña = JReseña.getText();
        String info = JInfo.getText();
        int categoria = (Jlista.getSelectedIndex() + 1);

        String categoryString = Jlista.getSelectedItem().toString();
//        boolean sCategory = searchCategory(base, categoryString);             //CREAR CATEGORIA NUEVA - por implementar
        //ObtenerInfo(categoryString);//
        if (base.crearConexion()) {
            sitioTemp = new Sitios_Interes(nombre, dir, calificacion, reseña, horario, info, categoria);
            //Se agrega el sitio a la bd
            base.insert(sitioTemp.insert());
            //se agrega la informacion buscada
            LinkedList<Object> idsSitio = base.select("select idSitio from sitios_interes, categorias "
                    + "WHERE idCategoria=idCategoriaS and nombreCategoria='" + categoryString + "'");
            int idSitio = (int) idsSitio.getLast();

            Contenidos_Multimedia contTemp = new Contenidos_Multimedia(idSitio, ven.cuenta.getCorreo());
            base.insert(contTemp.insert());

            LinkedList<Object> idsCont = base.select("select idContenido from "
                    + "contenidos_multimedia where idSitiosc=" + idSitio + "");
            int idCont = (int) idsCont.getLast();

            img = new Imagenes(nombre, reseña, imagen, idCont);
            base.insertImage(img);
        }
    }//GEN-LAST:event_JinsertActionPerformed

    private void JAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAddActionPerformed

        BaseDatos base = new BaseDatos();
        imagen = Imagenes.cargarArchivos();
        JImagen.setIcon(imagen);
        Jinsert.setEnabled(true);

    }//GEN-LAST:event_JAddActionPerformed

    private void JModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JModActionPerformed
        // TODO add your handling code here:

        Modificar mod = new Modificar(ven);
        ven.setContentPane(mod);
        ven.setSize(850, 490);

    }//GEN-LAST:event_JModActionPerformed

    private void JReseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JReseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JReseñaActionPerformed

    private void JAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAtrasActionPerformed
        // TODO add your handling code here:

        jPCuenta jPCuenta = new jPCuenta(ven);
        ven.setContentPane(jPCuenta);
        ven.setSize(410, 350);

    }//GEN-LAST:event_JAtrasActionPerformed

    private void JDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDeleteActionPerformed
        // TODO add your handling code here:
        Delete delete = new Delete(ven);
        ven.setContentPane(delete);
        ven.setSize(850, 490);


    }//GEN-LAST:event_JDeleteActionPerformed
    public void ObtenerInfo(String caso) {

        BaseDatos db = new BaseDatos();
        LinkedList<Object> listTemp;
        String sql = "SELECT sitios_interes.* FROM categorias, sitios_interes "
                + "WHERE idCategoria=idCategoriaS and nombreCategoria='" + caso + "'";

        System.out.println(sql);
        if (db.crearConexion()) {
            LinkedList<Object> list = db.select(sql);
            int size = list.size();
            int cant = size / 8;

            System.out.println("cantidad :" + cant);
            for (int i = 0; i < cant; i++) {
                listTemp = new LinkedList<>();
                for (int j = 0; j < 8; j++) {
                    if (!list.isEmpty()) {
                        listTemp.add(list.removeFirst());
                    }
                }

                Sitios_Interes sitio = new Sitios_Interes();
                sitio.read(listTemp);
                sitios.add(sitio);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAdd;
    private javax.swing.JButton JAtras;
    private javax.swing.JComboBox<String> JCalificacion;
    private javax.swing.JButton JDelete;
    private javax.swing.JTextField JDireccion;
    private javax.swing.JTextField JHorario;
    private javax.swing.JLabel JImagen;
    private javax.swing.JTextField JInfo;
    private javax.swing.JButton JMod;
    private javax.swing.JTextField JNombre;
    private javax.swing.JTextField JReseña;
    private javax.swing.JButton Jinsert;
    private javax.swing.JComboBox<String> Jlista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    /* private boolean searchCategory(BaseDatos base, String category) {
    
    String sql = "Select * from categorias where nombreCategoria=" + category + "";
    LinkedList<Object> select = base.select(sql);
    
    return !select.isEmpty();
    }*/
}
