/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import database.BaseDatos;
import entidades.Contenidos_Multimedia;
import entidades.Cuentas;
import entidades.Imagenes;
import entidades.Sitios_Interes;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author CATV
 */
public class MenuAdmin extends JPanel {

    Ventana ven;
    Sitios_Interes sitios;
    ImageIcon imagen;

    /**
     * Creates new form PAg
     *
     * @param ven
     */
    public MenuAdmin(Ventana ven) {
        initComponents();
        this.ven = ven;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlista = new javax.swing.JComboBox<>();
        Jinsert = new javax.swing.JButton();
        JDelete = new javax.swing.JButton();
        JMod = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JDireccion = new javax.swing.JTextField();
        JInfo = new javax.swing.JTextField();
        JCalificacion = new javax.swing.JComboBox<>();
        JReseña = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JHorario = new javax.swing.JTextField();
        JImagen = new javax.swing.JLabel();
        JAdd = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(662, 374));
        setLayout(null);

        Jlista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro Comercial", "Hotel", "Restaurante" }));
        Jlista.setSelectedIndex(1);
        add(Jlista);
        Jlista.setBounds(50, 10, 209, 27);

        Jinsert.setText("Insertar");
        Jinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JinsertActionPerformed(evt);
            }
        });
        add(Jinsert);
        Jinsert.setBounds(220, 310, 92, 29);

        JDelete.setText("Borrar");
        add(JDelete);
        JDelete.setBounds(29, 391, 81, 29);

        JMod.setText("Modificar");
        add(JMod);
        JMod.setBounds(128, 391, 103, 29);

        jLabel1.setText("Nombre");
        add(jLabel1);
        jLabel1.setBounds(60, 50, 50, 16);
        add(JNombre);
        JNombre.setBounds(150, 40, 223, 26);

        jLabel2.setText("Direccion");
        add(jLabel2);
        jLabel2.setBounds(60, 80, 60, 16);

        jLabel3.setText("Calificacion");
        add(jLabel3);
        jLabel3.setBounds(60, 110, 74, 16);

        jLabel4.setText("Reseña");
        add(jLabel4);
        jLabel4.setBounds(70, 170, 44, 16);

        jLabel5.setText("Informacion adicional");
        add(jLabel5);
        jLabel5.setBounds(10, 240, 137, 16);
        add(JDireccion);
        JDireccion.setBounds(150, 70, 223, 26);
        add(JInfo);
        JInfo.setBounds(150, 240, 223, 66);

        JCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        JCalificacion.setSelectedIndex(1);
        add(JCalificacion);
        JCalificacion.setBounds(160, 100, 64, 27);
        add(JReseña);
        JReseña.setBounds(150, 170, 223, 66);

        jLabel6.setText("Horario");
        add(jLabel6);
        jLabel6.setBounds(60, 140, 47, 16);
        add(JHorario);
        JHorario.setBounds(150, 140, 223, 26);
        add(JImagen);
        JImagen.setBounds(400, 30, 220, 230);

        JAdd.setText("Agregar");
        JAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAddActionPerformed(evt);
            }
        });
        add(JAdd);
        JAdd.setBounds(460, 280, 93, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void JinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JinsertActionPerformed

        BaseDatos base = new BaseDatos();
        Contenidos_Multimedia cont = null;
        Cuentas cuenta = ven.cuenta;
        Sitios_Interes sitiotemp = new Sitios_Interes();
        Imagenes img = new Imagenes();

        String nombre = JNombre.getText();
        String Dir = JDireccion.getText();
        int Calificacion = new Integer(JCalificacion.getSelectedItem().toString());
        String Horario = JHorario.getText();
        String reseña = JReseña.getText();
        String info = JInfo.getText();
        int Categoria = (Jlista.getSelectedIndex() + 1);

        switch (Jlista.getSelectedItem().toString()) {

            case "Centro Comercial":

                sitios = new Sitios_Interes(nombre, Dir, Calificacion, reseña, Horario, info, Categoria);

                if (base.crearConexion()) {
                    //Se agrega el sitio a la bd
                    base.insert(sitios.insert());
                    //Se busca el idSitio y el correo de quien este agregando
                    
                    
                    
                    
                    
                    System.out.println(cuenta.getCorreo());
                        //se agrega la informacion buscada
                        cont = new Contenidos_Multimedia(sitios.getIdSitio(), cuenta.getCorreo());
                        //Se agrega el contenido_multimeida a la bd
                        System.out.println(cont.toString());

                        base.insert(cont.insert());

                        img = new Imagenes(imagen.getDescription(), sitiotemp.getReseña(), imagen, cont.getIdContenido());
                        //Se agrega Imagenes a la bd
                        System.out.println(img.toString());
                        base.insertImage(img);

                    
                }

                break;

            case "Hotel":

                sitios = new Sitios_Interes(nombre, Dir, Calificacion, reseña, Horario, info, Categoria);
                if (base.crearConexion()) {
                    base.insert(sitios.insert());

                }

                break;
            case "Restaurante":

                sitios = new Sitios_Interes(nombre, Dir, Calificacion, reseña, Horario, info, Categoria);
                if (base.crearConexion()) {
                    base.insert(sitios.insert());

                }

                break;

        }


    }//GEN-LAST:event_JinsertActionPerformed

    private void JAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAddActionPerformed

        BaseDatos base = new BaseDatos();
        imagen = Imagenes.cargarArchivos();
        JImagen.setIcon(imagen);

    }//GEN-LAST:event_JAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAdd;
    private javax.swing.JComboBox<String> JCalificacion;
    private javax.swing.JButton JDelete;
    private javax.swing.JTextField JDireccion;
    private javax.swing.JTextField JHorario;
    private javax.swing.JLabel JImagen;
    private javax.swing.JTextField JInfo;
    private javax.swing.JButton JMod;
    private javax.swing.JTextField JNombre;
    private javax.swing.JTextField JReseña;
    private javax.swing.JButton Jinsert;
    private javax.swing.JComboBox<String> Jlista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
