/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lugares;

import Ventana.Ventana;
import javax.swing.ImageIcon;

/**
 *
 * @author CATV
 */
public class PagInfo extends javax.swing.JPanel {

    Ventana ven;

    /**
     * Creates new form PAg
     */
    public PagInfo(Ventana ven) {
        initComponents();
        LCentroC.setIcon(new ImageIcon("src/Lugares/Goku_ssj_4_kamehameha_x10.gif"));
        LZoo.setIcon(new ImageIcon("src/Lugares/000aa_Hypnotoad_animated.gif"));
        LSitios.setIcon(new ImageIcon("src/Lugares/2-Ninja-150x100.gif"));
        LHotel.setIcon(new ImageIcon("src/Lugares/huevo-imagen-animada-0022.gif"));
        LRestaurante.setIcon(new ImageIcon("src/Lugares/luces_disco.gif"));
        LMuseo.setIcon(new ImageIcon("src/Lugares/mirajane_3_by_salamanderkaze-d32mlde.gif"));
        this.ven = ven;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        LMuseo = new javax.swing.JLabel();
        LRestaurante = new javax.swing.JLabel();
        LHotel = new javax.swing.JLabel();
        LCentroC = new javax.swing.JLabel();
        LSitios = new javax.swing.JLabel();
        LZoo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(662, 374));
        setSize(new java.awt.Dimension(672, 374));
        setLayout(null);

        jLabel3.setText("Centro Comercial");
        add(jLabel3);
        jLabel3.setBounds(70, 140, 109, 16);
        add(LMuseo);
        LMuseo.setBounds(250, 30, 150, 100);
        add(LRestaurante);
        LRestaurante.setBounds(450, 30, 150, 100);

        LHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LHotelMouseClicked(evt);
            }
        });
        add(LHotel);
        LHotel.setBounds(50, 180, 150, 100);

        LCentroC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LCentroCMouseClicked(evt);
            }
        });
        add(LCentroC);
        LCentroC.setBounds(50, 30, 150, 100);
        add(LSitios);
        LSitios.setBounds(250, 180, 145, 100);
        add(LZoo);
        LZoo.setBounds(450, 180, 150, 100);

        jLabel13.setText("Hotel");
        add(jLabel13);
        jLabel13.setBounds(110, 290, 34, 16);

        jLabel14.setText("Museo");
        add(jLabel14);
        jLabel14.setBounds(300, 140, 41, 16);

        jLabel15.setText("Restaurantes");
        add(jLabel15);
        jLabel15.setBounds(480, 140, 81, 16);

        jLabel16.setText("Sitios de interes");
        add(jLabel16);
        jLabel16.setBounds(270, 290, 101, 16);

        jLabel17.setText("Zoologico");
        add(jLabel17);
        jLabel17.setBounds(490, 290, 63, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void LCentroCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCentroCMouseClicked

        System.out.println("holaa ");

    }//GEN-LAST:event_LCentroCMouseClicked

    private void LHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LHotelMouseClicked
        // TODO add your handling code here:
        jPSitiosInteres sitio = new jPSitiosInteres("Hotel");
        ven.setContentPane(sitio);
        ven.setSize(900, 650);


    }//GEN-LAST:event_LHotelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCentroC;
    private javax.swing.JLabel LHotel;
    private javax.swing.JLabel LMuseo;
    private javax.swing.JLabel LRestaurante;
    private javax.swing.JLabel LSitios;
    private javax.swing.JLabel LZoo;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
