/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Multimedia;

import Datos.Comentario;
import javax.swing.JOptionPane;

/**
 *
 * @author CATV
 */
public class jPComentario extends javax.swing.JPanel {

    public jPComentario() {
        initComponents();
        JComentario.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JComentario = new javax.swing.JTextArea();
        JAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNext = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(310, 110));
        setSize(new java.awt.Dimension(310, 110));

        JComentario.setColumns(20);
        JComentario.setRows(5);
        JComentario.setBorder(null);

        JAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/circle.png"))); // NOI18N
        JAdd.setPreferredSize(new java.awt.Dimension(32, 32));
        JAdd.setSize(new java.awt.Dimension(32, 32));
        JAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Comentario");

        jNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Next.png"))); // NOI18N
        jNext.setPreferredSize(new java.awt.Dimension(32, 32));
        jNext.setSize(new java.awt.Dimension(32, 32));
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JComentario, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAddActionPerformed
        // TODO add your handling code here:
        String comen = JOptionPane.showInputDialog("add comentario");

        Comentario comentario = new Comentario(1, comen);
        JComentario.setText(comentario.getTexto());
    }//GEN-LAST:event_JAddActionPerformed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        // TODO add your handling code here:
        Comentario comentario = new Comentario();
        JComentario.setText(comentario.getTexto());
        System.out.println("Comntario");

    }//GEN-LAST:event_jNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAdd;
    private javax.swing.JTextArea JComentario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNext;
    // End of variables declaration//GEN-END:variables
}
