/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Datos.Cuentas;
import database.BaseDatos;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author CATV
 */
public class Ajustes extends javax.swing.JPanel {

    /**
     * Creates new form Ajustes
     */
    Ventana ven;
    Cuentas cuenta;
    String correo;

    public Ajustes(Ventana ven, String correo) {
        this.ven = ven;
        this.correo = correo;
        initComponents();
        cuenta = new Cuentas();
    }

    public Ajustes() {
        initComponents();
    }

    public boolean Recuperar() {

        boolean flag = false;
        BaseDatos base = new BaseDatos();
        String cifrado = Cuentas.Encriptar(PedirContra('v'));
        Cuentas cuenta2 = new Cuentas(correo);

        if (base.crearConexion()) {
            LinkedList<Object> list = base.read(cuenta2.select());

            cuenta.read(list);

            if (cifrado.equals(cuenta.getPassword())) {

                jNombre.setText(cuenta.getNombre());
                jApellido.setText(cuenta.getApellido());
                jCelular.setText(cuenta.getCelular());

                flag = true;

            } else {
                flag = false;
            }
        }

        return flag;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jApellido = new javax.swing.JTextField();
        BtActualizar = new javax.swing.JButton();
        jCelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        BtCambiar = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(400, 300));
        setLayout(null);

        jLabel1.setText("Celular");
        add(jLabel1);
        jLabel1.setBounds(69, 113, 50, 16);
        add(jApellido);
        jApellido.setBounds(137, 76, 198, 26);

        BtActualizar.setText("Actualizar");
        BtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtActualizarActionPerformed(evt);
            }
        });
        add(BtActualizar);
        BtActualizar.setBounds(170, 150, 107, 29);
        add(jCelular);
        jCelular.setBounds(137, 108, 198, 26);

        jLabel3.setText("Nombre");
        add(jLabel3);
        jLabel3.setBounds(69, 49, 50, 16);

        jLabel4.setText("Apellido");
        add(jLabel4);
        jLabel4.setBounds(69, 81, 52, 16);

        jNombre.setToolTipText("");
        add(jNombre);
        jNombre.setBounds(137, 44, 198, 26);

        BtCambiar.setText("Modificar");
        BtCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCambiarActionPerformed(evt);
            }
        });
        add(BtCambiar);
        BtCambiar.setBounds(170, 210, 103, 29);

        BtEliminar.setText("Eliminar");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });
        add(BtEliminar);
        BtEliminar.setBounds(180, 250, 95, 29);

        jLabel7.setText("Eliminar cuenta");
        add(jLabel7);
        jLabel7.setBounds(60, 250, 110, 16);

        jLabel8.setText("Modificar contraseña");
        add(jLabel8);
        jLabel8.setBounds(20, 210, 132, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void BtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtActualizarActionPerformed

        String Contraseña = JOptionPane.showInputDialog("Ingrese contraseña, para guardar");

        String cifrado = Cuentas.Encriptar(Contraseña);

        System.out.println("cifrado " + cifrado);

        System.out.println("cuenta  " + cuenta.toString());

        BaseDatos base = new BaseDatos();
        if (base.crearConexion()) {

            if (cifrado.equals(cuenta.getPassword())) {
                String Nombre = jNombre.getText();
                String Apellido = jApellido.getText();
                String Celular = jCelular.getText();
                String Correo = cuenta.getCorreo();

                cuenta = new Cuentas(Correo, cifrado, Nombre, Apellido, Celular);

                base.update(cuenta.update('c'));

                System.out.println("UPDATE: " + cuenta.update('c'));

                jPCuenta reg = new jPCuenta(ven);
                ven.setContentPane(reg);
                ven.setSize(410, 350);

            }
        } else {
            JOptionPane.showMessageDialog(null, "La contraseña no coincide");

        }


    }//GEN-LAST:event_BtActualizarActionPerformed

    public String PedirContra(char c) {
        String password = null;
        JPasswordField pf;

        switch (c) {
            case 'v':
                pf = new JPasswordField();
                int pPass = JOptionPane.showConfirmDialog(null, pf, "Ingrese contraseña", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (pPass == JOptionPane.OK_OPTION) {
                    password = new String(pf.getPassword());
                    System.err.println("You entered: " + password);
                }
                break;

            case 'n':
                pf = new JPasswordField();
                int pPass2 = JOptionPane.showConfirmDialog(null, pf, "Ingrese contraseña nueva", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (pPass2 == JOptionPane.OK_OPTION) {
                    password = new String(pf.getPassword());
                    System.err.println("You entered: " + password);
                }
                break;

        }
        return password;

    }

    private void BtCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCambiarActionPerformed

        String cifrado = Cuentas.Encriptar(PedirContra('v'));
        BaseDatos base = new BaseDatos();
        if (base.crearConexion()) {
            if (cifrado.equals(cuenta.getPassword())) {

                String cifrada = Cuentas.Encriptar(PedirContra('n'));

                String Correo = cuenta.getCorreo();

                cuenta = new Cuentas(Correo, cifrada);

                base.update(cuenta.update('p'));

                JOptionPane.showMessageDialog(null, "Cambio realizado");

                jPCuenta reg = new jPCuenta(ven);
                ven.setContentPane(reg);
                ven.setSize(410, 350);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña invalida");

        }


    }//GEN-LAST:event_BtCambiarActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed

        String cifrado = Cuentas.Encriptar(PedirContra('v'));
        BaseDatos base = new BaseDatos();
        if (base.crearConexion()) {
            if (cifrado.equals(cuenta.getPassword())) {

                String Correo = cuenta.getCorreo();

                System.out.println("correo :" + Correo);

                cuenta = new Cuentas(Correo, cifrado);

                base.delete(cuenta.delete());

                JOptionPane.showMessageDialog(null, "Cuenta eliminada");

                System.exit(0);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña invalida");

        }

    }//GEN-LAST:event_BtEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtActualizar;
    private javax.swing.JButton BtCambiar;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JTextField jApellido;
    private javax.swing.JTextField jCelular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNombre;
    // End of variables declaration//GEN-END:variables
}
