/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Datos.Cuentas;
import database.BaseDatos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CATV
 */
public class Registro extends javax.swing.JPanel {

    Ventana ven;
    Cuentas cuenta;

    public Registro(Ventana ven) {
        initComponents();
        this.ven = ven;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCelular = new javax.swing.JTextField();
        JPasscon = new javax.swing.JPasswordField();
        BtCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCorreo = new javax.swing.JTextField();
        jNombre = new javax.swing.JTextField();
        JPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setToolTipText("Cuenta");
        setPreferredSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(400, 300));
        setLayout(null);

        jLabel1.setText("Celular");
        add(jLabel1);
        jLabel1.setBounds(69, 113, 50, 16);

        jLabel2.setText("Confirmar");
        add(jLabel2);
        jLabel2.setBounds(60, 210, 71, 16);
        add(jCelular);
        jCelular.setBounds(137, 108, 198, 26);

        JPasscon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPassconActionPerformed(evt);
            }
        });
        add(JPasscon);
        JPasscon.setBounds(140, 200, 198, 26);

        BtCrear.setText("Crear");
        BtCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCrearActionPerformed(evt);
            }
        });
        add(BtCrear);
        BtCrear.setBounds(174, 233, 77, 29);

        jLabel3.setText("Nombre");
        add(jLabel3);
        jLabel3.setBounds(69, 49, 50, 16);

        jLabel4.setText("Apellido");
        add(jLabel4);
        jLabel4.setBounds(69, 81, 52, 16);
        add(jApellido);
        jApellido.setBounds(137, 76, 198, 26);

        jLabel6.setText("Correo");
        add(jLabel6);
        jLabel6.setBounds(70, 150, 42, 16);
        add(jCorreo);
        jCorreo.setBounds(137, 140, 198, 26);
        add(jNombre);
        jNombre.setBounds(137, 44, 198, 26);

        JPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPassActionPerformed(evt);
            }
        });
        add(JPass);
        JPass.setBounds(137, 172, 198, 26);

        jLabel5.setText("Contraseña");
        add(jLabel5);
        jLabel5.setBounds(50, 180, 71, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void JPassconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPassconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPassconActionPerformed


    private void BtCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCrearActionPerformed

        try {
            BaseDatos base = new BaseDatos();
            if (base.crearConexion()) {
                if (new String(JPass.getPassword()).equals(new String(JPasscon.getPassword()))) {
                    String Nombre = jNombre.getText();
                    String Apellido = jApellido.getText();
                    String Celular = jCelular.getText();
                    String Correo = jCorreo.getText();

                    String Contraseña = new String(JPasscon.getPassword());
                    String cifrado = Cuentas.Encriptar(Contraseña);

                    cuenta = new Cuentas(Correo, cifrado, Nombre, Apellido, Celular);

                    base.insert(cuenta.insert());

                    jPCuenta reg = new jPCuenta(ven);
                    ven.setContentPane(reg);
                    ven.setSize(410, 350);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La contraseña no coincide");

            }

        } catch (Exception ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtCrearActionPerformed

    private void JPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCrear;
    private javax.swing.JPasswordField JPass;
    private javax.swing.JPasswordField JPasscon;
    private javax.swing.JTextField jApellido;
    private javax.swing.JTextField jCelular;
    private javax.swing.JTextField jCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNombre;
    // End of variables declaration//GEN-END:variables
}
